BFS and DFS Implementation in Java
Ashrockzzz2003/Data_Structures_and_Algorithms pull request #50
Opened 2024-12-23 13:48 UTC by MithileshwaranS

2024-12-24 10:04 UTC, Ashrockzzz2003 requested changes
Why a class for DFS. I feel we can have a graph node class with a dfs function in it. Makes more sense.

Added some readability comments too. Work on them.

Files can be moved to `non_linear/graphs/bfs/bfs.java` 
and 
`non_linear/graphs/dfs/dfs.java`

2024-12-24 10:04 UTC, Ashrockzzz2003 commented on non_linear/graphs/BFS.java
> +        boolean visit[] = new boolean[vertex];//visited array is created
Comments can be better formatted as
`// Sentence.`

It's a good practice to leave a `space` after comment token. The upper and lower cases, can be handled the same way like how it's done in English. Comments can end with a fullstop.

2024-12-24 10:04 UTC, Ashrockzzz2003 commented on non_linear/graphs/BFS.java
> +        ArrayList<ArrayList<Integer>> adjacent = new ArrayList<>();
instead of comments here,
make the variable names to be self-explanatory.

2024-12-24 10:04 UTC, Ashrockzzz2003 commented on non_linear/graphs/BFS.java
> +
can be removed. probably from a debugging session ig.

2024-12-24 10:04 UTC, Ashrockzzz2003 commented on non_linear/graphs/BFS.java
> +import java.util.Arrays;
remove unused import.

2024-12-24 10:04 UTC, Ashrockzzz2003 commented on non_linear/graphs/DFS.java
> +
please remove empty lines on top.

2024-12-24 10:04 UTC, Ashrockzzz2003 commented on non_linear/graphs/DFS.java
> +        ArrayList<ArrayList<Integer>> adj = new ArrayList<>();
use self-explanatory var names.

2024-12-26 18:05 UTC, MithileshwaranS commented
@Ashrockzzz2003 Changes are done as per mentioned

2025-01-05 15:29 UTC, Ashrockzzz2003 approved these changes

2025-01-05 15:44 UTC, Ashrockzzz2003 commented
@MithileshwaranS 
I want your review!

2025-01-07 13:09 UTC, Ashrockzzz2003 commented
@MithileshwaranS 
Add yourself to `README`. We'll merge it.

2025-01-14 11:49 UTC, Ashrockzzz2003 commented
/bounty 20 @MithileshwaranS

2025-01-14 11:49 UTC, merged