Implement Multi-threaded Merge Sort in Java and Rust
Ashrockzzz2003/Data_Structures_and_Algorithms pull request #53
Opened 2024-12-23 16:17 UTC by KiranRajeev-KV

# PR: Implement Multi-threaded Merge Sort in Java and Rust

This PR adds the implementation of **Multi-threaded Merge Sort** in both **Java** and **Rust**, as stated in issue #42.

###  Added Features
- **Normal Merge Sort**: Implemented Normal Merge Sort in both Java and Rust. (this serves as the base implementation to build the Parallel Merge Sort)
- **Parallel Merge Sort**: Implemented a Parallel Merge Sort in both Java and Rust

### Changes Made
- Updated `.gitignore` to exclude `target` and `debug` folders from Cargo
- Updated `README.md` to add instructions for Rust code execution using Cargo

2025-01-01 11:22 UTC, FirefoxSRV requested changes
I have given my review for your code @KiranRajeev-KV

2025-01-01 11:22 UTC, FirefoxSRV commented on sorting/merge_sort/java_implementation/MergeSort.java
> +            int[] left = new int[mid];
Hi, this could fail if there is a null array (NOT EMPTY). [ NullPointerException is bound to occur] .......

2025-01-01 11:22 UTC, FirefoxSRV commented on sorting/merge_sort/java_implementation/MergeSort.java
> +            int[] left = new int[mid];
For very large arrays, int mid = arr.length / 2; could lead to integer overflow if arr.length exceeds Integer.MAX_VALUE (unlikely but theoretically possible).

2025-01-01 11:22 UTC, FirefoxSRV commented on sorting/merge_sort/java_implementation/ParallelMergeSort.java
> +    private static final int THRESHOLD = 5;
Isn't the THRESHOLD = 5 seem to look too low ? For performance measurement with small arrays, creating threads is more expensive than sorting them sequentially.

2025-01-23 11:32 UTC, KiranRajeev-KV commented on sorting/merge_sort/java_implementation/ParallelMergeSort.java
> +    private static final int THRESHOLD = 5;
Updated the threshold.

2025-01-23 11:32 UTC, KiranRajeev-KV commented on sorting/merge_sort/java_implementation/MergeSort.java
> +            int[] left = new int[mid];
Added a check for null arrays

2025-03-01 15:19 UTC, Ashrockzzz2003 reviewed
Have the normal and parallel sorts in the same file so that we can have it in the repo as a single file. Organize files and folders like every other algorithm please. Remove files generated during run such as `.lock` and `.toml`. Just the `.rs` and `.java` code will do. Add documentation instead on how to execute them

Will merge it after tht!

2025-03-01 15:20 UTC, Ashrockzzz2003 commented
/bounty 50 @KiranRajeev-KV

2025-07-05 17:56 UTC, merged